### ISSUE TITLE
无法下载模型，怎么操作呢？

### ISSUE THREAD

**Issue by tyn513** [StanleyLsx/sequence_labeling#26]
由于网络无法直接下载模型。
手动下载后报错：OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5'] found in directory chinese or `from_pt` set to False

**Comment by stanleylsx** [comment]
> 由于网络无法直接下载模型。 手动下载后报错：OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5'] found in directory chinese or `from_pt` set to False

文件不存在。而且你这里加载的是torch的模型？
