### ISSUE TITLE
文章出现\t 和空格时会报错

### ISSUE THREAD

**Issue by tyn513** [StanleyLsx/sequence_labeling#30]
文章出现\t 和空格时会报错

token, token_id = row.split('\t')[0], int(row.split('\t')[1])
IndexError: list index out of range

**Comment by stanleylsx** [comment]
> 文章出现\t 和空格时会报错
> 
> token, token_id = row.split('\t')[0], int(row.split('\t')[1]) IndexError: list index out of range

已解决

**Comment by 2506791459** [comment]
怎样解决的呀

**Comment by guo-xiaomeng** [comment]
同样的问题，没有解决
