### ISSUE TITLE
train_dataset, val_dataset = data_manager.get_training_set()两个返回TensorSliceDataset无法用len函数

### ISSUE THREAD

**Issue by formytest2** [StanleyLsx/sequence_labeling#34]
train.py:
train_dataset, val_dataset = data_manager.get_training_set()两个返回TensorSliceDataset无法用len函数
报错TypeError: object of type 'TensorSliceDataset' has no len()
tensorflow版本v2.2.0
我试了几个版本，都不支持len

**Comment by stanleylsx** [comment]
> train.py: train_dataset, val_dataset = data_manager.get_training_set()两个返回TensorSliceDataset无法用len函数 报错TypeError: object of type 'TensorSliceDataset' has no len() tensorflow版本v2.2.0 我试了几个版本，都不支持len

我降级为2.2没有出现这个问题哦，是不是你的数据集没有加载成功？

**Comment by zhaoyu123213** [comment]
> train.py: train_dataset, val_dataset = data_manager.get_training_set()两个返回TensorSliceDataset无法用len函数 报错TypeError: object of type 'TensorSliceDataset' has no len() tensorflow版本v2.2.0 我试了几个版本，都不支持len

你好请问你最后解决了吗，我也出现了这个问题
