### ISSUE TITLE
python版本

### ISSUE THREAD

**Issue by NanshineLoong** [StanleyLsx/sequence_labeling#50]
是不是必须用Python3.7才能无错安装依赖

**Comment by NanshineLoong** [comment]
用Python3.8会在下面这两行之后报一大堆错
```
Building wheels for collected packages: numpy
  Building wheel for numpy (setup.py) ... \
```

用python3.7会出现不能使用GPU的情况：
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/100546876/177893926-b3dd419d-1e3c-4bb5-ad87-32dd8354d0f2.png">

**Comment by stanleylsx** [comment]
> 

你要安装cudnn和cudn才能使用，具体参考这篇文章https://blog.csdn.net/Flying_sfeng/article/details/109777300
