### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by 17478020** [StanleyLsx/sequence_labeling#51]
您好！我改成mode=train训练模式之后，在训练过程中就报错
![image](https://user-images.githubusercontent.com/63388342/190111857-c9c247d3-018d-4955-98ea-9f92a8b150b0.png)

**Comment by stanleylsx** [comment]
> 您好！我改成mode=train训练模式之后，在训练过程中就报错 ![image](https://user-images.githubusercontent.com/63388342/190111857-c9c247d3-018d-4955-98ea-9f92a8b150b0.png)

fixed
