### ISSUE TITLE
更换预训练模型，比如albert

### ISSUE THREAD

**Issue by hanxun0121** [StanleyLsx/sequence_labeling#52]
up主，请问代码中，如果要更换预训练模型albert，需要除了需要修改system.config之外，还需要修改那些地方呢？

**Comment by hanxun0121** [comment]
如何从本地加载下载好的预训练模型呢？

**Comment by July199** [comment]
> 如何从本地加载下载好的预训练模型呢？

您好，请问您现在知道如何解决“更换本地的预训练模型”这个问题么？

**Comment by stanleylsx** [comment]
已支持Albert，使用的Albert参数为https://huggingface.co/uer/albert-base-chinese-cluecorpussmall
