### ISSUE TITLE
当我训练完bilstm-crf和idcnn-crf模型的时候，开始训练bert-bilstm-crf模型，老是报错

### ISSUE THREAD

**Issue by Hzzhang-nlp** [StanleyLsx/sequence_labeling#55]
![image](https://user-images.githubusercontent.com/39661319/208305667-b6366ec9-2ab5-442a-885e-3f7fbd8e664e.png)

**Comment by Hzzhang-nlp** [comment]
希望作者能帮我解决一下，试了很多方法都没改好

**Comment by stanleylsx** [comment]
fixed
