### ISSUE TITLE
将自己的数据集分为四类替换进去并且修改了suffix里面的标签为自己的标签 ，出现如下错误

### ISSUE THREAD

**Issue by 2506791459** [StanleyLsx/sequence_labeling#57]
![image](https://user-images.githubusercontent.com/120935682/226171497-020d95bb-1679-416c-994f-6d20d80a33e6.png)

**Comment by stanleylsx** [comment]
> ![image](https://user-images.githubusercontent.com/120935682/226171497-020d95bb-1679-416c-994f-6d20d80a33e6.png)

fixed

**Comment by 2506791459** [comment]
我之前是因为数据集的标签出现了一个错误，然后显示这个问题，我修改正确我的标签后，问题就解决了，但是查找哪个标签有问题是一件比较耗费时间的事情 &nbsp;


百里沐苏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月14日(星期四) 下午5:04
收件人: "StanleyLsx/entity_extractor_by_ner";
抄送: "Author";
主题: Re: [StanleyLsx/entity_extractor_by_ner] 将自己的数据集分为四类替换进去并且修改了suffix里面的标签为自己的标签 ，出现如下错误 (Issue #57)





  

  
fixed
 
&mdash;
