### ISSUE TITLE
idcnn训练时出现准确率和召回率全0

### ISSUE THREAD

**Issue by ChemEng227** [StanleyLsx/sequence_labeling#60]
![image](https://github.com/StanleyLsx/entity_extractor_by_ner/assets/76087681/eae698a7-b3c8-4411-be2d-2efe388dcbc9)

如图，尝试训练IDCNN-CRF模型时，出现准确和召回率全0且训练无改善，数个Epoch后loss变为NaN的情况，应该怎么解决？

**Comment by stanleylsx** [comment]
> ![image](https://user-images.githubusercontent.com/76087681/244257866-eae698a7-b3c8-4411-be2d-2efe388dcbc9.png)
> 
> 如图，尝试训练IDCNN-CRF模型时，出现准确和召回率全0且训练无改善，数个Epoch后loss变为NaN的情况，应该怎么解决？

数据集的大小和分布如何？

**Comment by stanleylsx** [comment]
我使用demo数据直接跑idcnn没有出现这个问题，训练结果和文件会更新上来，大概率数据欠拟合，建议增加数据集或者增大学习率。
或者使用bert作为embedding或者把bert加入的微调中。
