### ISSUE TITLE
Idcnn+crf 无法训练

### ISSUE THREAD

**Issue by leizhengtao520** [StanleyLsx/sequence_labeling#63]
3%|▎         | 20/725 [00:03<02:07,  5.53it/s]training batch:    20, loss: 21.37336, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.890 
  6%|▌         | 40/725 [00:07<01:55,  5.94it/s]training batch:    40, loss: 1131.92053, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.856 
  8%|▊         | 60/725 [00:11<02:00,  5.52it/s]training batch:    60, loss: 208.67366, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.889 
 11%|█         | 80/725 [00:15<01:57,  5.47it/s]training batch:    80, loss: 19.80162, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.880 
 14%|█▍        | 100/725 [00:18<01:43,  6.02it/s]training batch:   100, loss: 15.38830, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.899 
 17%|█▋        | 120/725 [00:22<01:45,  5.73it/s]training batch:   120, loss: 17.61979, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.875 
各项数据都为0 ，数据是本项目提供的，仅仅是改成训练模式。

**Comment by stanleylsx** [comment]
> 3%|▎ | 20/725 [00:03<02:07, 5.53it/s]training batch: 20, loss: 21.37336, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.890 6%|▌ | 40/725 [00:07<01:55, 5.94it/s]training batch: 40, loss: 1131.92053, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.856 8%|▊ | 60/725 [00:11<02:00, 5.52it/s]training batch: 60, loss: 208.67366, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.889 11%|█ | 80/725 [00:15<01:57, 5.47it/s]training batch: 80, loss: 19.80162, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.880 14%|█▍ | 100/725 [00:18<01:43, 6.02it/s]training batch: 100, loss: 15.38830, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.899 17%|█▋ | 120/725 [00:22<01:45, 5.73it/s]training batch: 120, loss: 17.61979, precision: 0.000 recall: 0.000 f1: 0.000 accuracy: 0.875 各项数据都为0 ，数据是本项目提供的，仅仅是改成训练模式。

增大学习率，或者前面加一个Bert.
