### ISSUE TITLE
equests.exceptions.SSLError:

### ISSUE THREAD

**Issue by bnjhzsdcgvd** [StanleyLsx/sequence_labeling#70]
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-chinese (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))
这种问题怎么解决哇，求救
what can i do to solve this problem
![1711729252160](https://github.com/stanleylsx/entity_extractor_by_ner/assets/68514747/dc545bd8-ea9d-4dee-bf0e-d29317272e9a)

**Comment by LELE-ZZ** [comment]
我也出现了这个报错，请问一下怎么解决的？
