### ISSUE TITLE
代码是否可以用在英文数据集上

### ISSUE THREAD

**Issue by niufendou** [StanleyLsx/sequence_labeling#71]
我下载了英文的预训练bert模型，并且把我自己的英文数据集处理了格式之后，放上去训练结果全是0，是不支持英文吗
![image](https://github.com/stanleylsx/entity_extractor_by_ner/assets/102421327/7e1ab77f-754a-4a3d-a0d9-422094f81d81)

**Comment by stanleylsx** [comment]
> 我下载了英文的预训练bert模型，并且把我自己的英文数据集处理了格式之后，放上去训练结果全是0，是不支持英文吗 ![image](https://private-user-images.githubusercontent.com/102421327/326339246-7e1ab77f-754a-4a3d-a0d9-422094f81d81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTc1NDUsIm5iZiI6MTcyNTI1NzI0NSwicGF0aCI6Ii8xMDI0MjEzMjcvMzI2MzM5MjQ2LTdlMWFiNzdmLTc1NGEtNGEzZC1hMGQ5LTQyMjA5NGY4MWQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwNjA3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzU0MDg4MDVmZWE5OWEwMzdkYjcxMTkyYjFhOTgxNDQ1ZTYyYWQ1MDA1YzU0ZGI0MjdmODBlYjY5NmViMWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fc8_Y8lYYr3DXPYMrLUoY8mEbkzlc1w5ybJUZvw9Kcc)

英文是支持的，不过你需要把英文的每个单词都标注成BIO格式才行，不过我建议使用https://github.com/stanleylsx/entity_extractor_by_pointer这个项目，标注格式没这么麻烦。
