### ISSUE TITLE
无法生成lab2id和token2id两个文件

### ISSUE THREAD

**Issue by bigenheng** [StanleyLsx/sequence_labeling#72]
![Snipaste_2024-05-10_21-19-22](https://github.com/stanleylsx/entity_extractor_by_ner/assets/115866701/494c574b-0548-43ed-bdea-6dcd034883b9)

**Comment by bigenheng** [comment]
你好，请问这个如何解决呢？

**Comment by M-YoungBWeN** [comment]
同问，我没有生成token2id

**Comment by M-YoungBWeN** [comment]
![0001](https://github.com/stanleylsx/entity_extractor_by_ner/assets/109461737/04964470-3feb-4299-84f2-c127f621d2b4)
在训练时使用预训练模型就不会生成token2id文件，那么预测时该使用哪个词表呢

**Comment by stanleylsx** [comment]
> ![0001](https://private-user-images.githubusercontent.com/109461737/341918316-04964470-3feb-4299-84f2-c127f621d2b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTc0MTYsIm5iZiI6MTcyNTI1NzExNiwicGF0aCI6Ii8xMDk0NjE3MzcvMzQxOTE4MzE2LTA0OTY0NDcwLTNmZWItNDI5OS04NGYyLWMxMjdmNjIxZDJiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwNjA1MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTU5NmM5YTAwOGU1MTM3NTQ2YjdhYjliN2Q4M2IxM2MzNDMxNDMzMTFiMDYwZTZlMjgxZjVlODM0YzNmYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KMt02N5GJVxXw7aaXBRRGAo6zTZL6x059SP4vPLvbjc) 在训练时使用预训练模型就不会生成token2id文件，那么预测时该使用哪个词表呢

预训练模型本身自己带有tokenizer，不需要生成token2id文件了。
