### ISSUE TITLE
更改为自己数据集后的训练问题

### ISSUE THREAD

**Issue by LELE-ZZ** [StanleyLsx/sequence_labeling#76]
请问一下作者
1.为啥bert-bilstm/idcnn-crf训练前五次评价结果都为0自动停止
2.bilstm/idcnn-crf模型训练时报错：Traceback (most recent call last):
  File "E:/project-NER/main.py", line 67, in <module>
    dataManager = DataManager(configs, logger)
  File "E:\project-NER\engines\data.py", line 40, in __init__
    self.token2id, self.id2token, self.label2id, self.id2label = self.load_vocab()
  File "E:\project-NER\engines\data.py", line 61, in load_vocab
    return self.build_vocab(self.train_file)
  File "E:\project-NER\engines\data.py", line 93, in build_vocab
    token2id = dict(zip(tokens, range(1, len(tokens) + 1)))
TypeError: unhashable type: 'list'

**Comment by stanleylsx** [comment]
> 请问一下作者 1.为啥bert-bilstm/idcnn-crf训练前五次评价结果都为0自动停止 2.bilstm/idcnn-crf模型训练时报错：Traceback (most recent call last): File "E:/project-NER/main.py", line 67, in dataManager = DataManager(configs, logger) File "E:\project-NER\engines\data.py", line 40, in **init** self.token2id, self.id2token, self.label2id, self.id2label = self.load_vocab() File "E:\project-NER\engines\data.py", line 61, in load_vocab return self.build_vocab(self.train_file) File "E:\project-NER\engines\data.py", line 93, in build_vocab token2id = dict(zip(tokens, range(1, len(tokens) + 1))) TypeError: unhashable type: 'list'

1. 疑似欠拟合，需要调大lr或者增加数据，特别是不用到Bert，很容易欠拟合不收敛；
2. 具体数据集是怎么样的？是不是按照例子里面的结构构造的。
